### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by apahl** [pyviz/jupyterlab_holoviews#2]
Hi, thanks for providing this extension.  
I use holoviews and bokeh a lot and would really like to switch to JupyterLab, but the fact that my charts do not show up in the JLab notebooks, even after installing this extension, keeps me from switching.

This is the code I run in the JLab notebook:
![holoviews](https://user-images.githubusercontent.com/9406836/38665651-3766a3cc-3e3d-11e8-9834-b6169ed96f94.png)

As you can see, the output cell remains completely empty. When I open the same notebook from the Jupyter **Notebook** server, the chart is there.

These are the messages I get during installation of the extension, I get an error for an **optional** dependency, but otherwise the installations seems to be successful:
```
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[-/2] ⡀ waiting...
[2/2] ⡀ canvas: CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
[-/2] ⡀ waiting...
[-/2] ⡀ waiting...
warning Error running install script for optional dependency: "/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.2\ngyp info using node@9.7.1 | linux | x64\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/home/pahl/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/pahl/.config/yarn/global/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/home/pahl/.node-gyp/9.7.1/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/home/pahl/.node-gyp/9.7.1',\ngyp info spawn args   '-Dnode_gyp_dir=/home/pahl/.config/yarn/global/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/home/pahl/.node-gyp/9.7.1/<(target_arch)/node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\ngyp info spawn make\ngyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]\nmake: Entering directory '/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas/build'\n  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node\n  COPY Release/canvas-postbuild.node\n  CXX(target) Release/obj.target/canvas/src/Canvas.o\nIn file included from ../src/Canvas.cc:20:0:\n../src/JPEGStream.h: In function ‘boolean empty_closure_output_buffer(j_compress_ptr)’:\n../src/JPEGStream.h:42:108: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, argv);\n                                                                                                            ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\nIn file included from ../src/Canvas.cc:20:0:\n../src/JPEGStream.h: In function ‘void term_closure_destination(j_compress_ptr)’:\n../src/JPEGStream.h:63:113: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, data_argv);\n                                                                                                                 ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\nIn file included from ../src/Canvas.cc:20:0:\n../src/JPEGStream.h:71:112: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, end_argv);\n                                                                                                                ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\n../src/Canvas.cc: In static member function ‘static void Canvas::ToBufferAsyncAfter(uv_work_t*)’:\n../src/Canvas.cc:221:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]\n     closure->pfn->Call(1, argv);\n                               ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:1618:3: note: declared here\n   Call(int argc, v8::Local<v8::Value> argv[]) const {\n   ^~~~\n../src/Canvas.cc:226:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]\n     closure->pfn->Call(2, argv);\n                               ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:1618:3: note: declared here\n   Call(int argc, v8::Local<v8::Value> argv[]) const {\n   ^~~~\n../src/Canvas.cc: In function ‘cairo_status_t streamPNG(void*, const uint8_t*, unsigned int)’:\n../src/Canvas.cc:377:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure->fn, 3, argv);\n                                                                                                      ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\n../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)’:\n../src/Canvas.cc:446:103: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);\n                                                                                                       ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\n../src/Canvas.cc:452:103: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);\n                                                                                                       ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\n../src/Canvas.cc: In function ‘cairo_status_t streamPDF(void*, const uint8_t*, unsigned int)’:\n../src/Canvas.cc:476:77: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]\n   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), closure->fn, 3, argv);\n                                                                             ^\nIn file included from ../src/Canvas.h:22:0,\n                 from ../src/Canvas.cc:7:\n../../nan/nan.h:929:46: note: declared here\n   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(\n                                              ^~~~~~~~~~~~\nIn file included from ../src/Canvas.cc:8:0:\n../src/PNG.h: In function ‘cairo_status_t canvas_write_png(cairo_surface_t*, png_rw_ptr, void*)’:\n../src/PNG.h:73:20: warning: variable ‘status’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]\n     cairo_status_t status = CAIRO_STATUS_SUCCESS;\n                    ^~~~~~\n  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o\n  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o\nIn file included from ../src/CanvasPattern.cc:9:0:\n../src/Image.h:19:10: fatal error: gif_lib.h: No such file or directory\n #include <gif_lib.h>\n          ^~~~~~~~~~~\ncompilation terminated.\ncanvas.target.mk:127: recipe for target 'Release/obj.target/canvas/src/CanvasPattern.o' failed\nmake: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1\nmake: Leaving directory '/home/pahl/anaconda3/envs/chem/share/jupyter/lab/staging/node_modules/canvas/build'\ngyp ERR! build error \ngyp ERR! stack Error: `make` failed with exit code: 2\ngyp ERR! stack     at ChildProcess.onExit (/home/pahl/.config/yarn/global/node_modules/node-gyp/lib/build.js:258:23)\ngyp ERR! stack     at ChildProcess.emit (events.js:127:13)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.5.1" while you're on "1.3.2".
Done in 42.17s.
> node /home/pahl/anaconda3/envs/chem/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
Hash: f26bb41f3cbb41a4dfb9
Version: webpack 2.7.0
Time: 37917ms
                                 Asset     Size  Chunks                    Chunk Names
        vendor.4b10ea08cbe243fbd96b.js  1.58 MB       3  [emitted]  [big]  vendor
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]         
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
             0.39dfc87784e4614a1bd9.js   621 kB       0  [emitted]  [big]  vega2
             1.697f116e8467e0f2ccc6.js   458 kB       1  [emitted]  [big]  
          main.b288fed0daf353d445f9.js  1.76 MB       2  [emitted]  [big]  main
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]         
      manifest.1a29b82ab404008e9de7.js  1.65 kB       4  [emitted]         manifest
         0.39dfc87784e4614a1bd9.js.map  2.29 MB       0  [emitted]         vega2
         1.697f116e8467e0f2ccc6.js.map  1.34 MB       1  [emitted]         
      main.b288fed0daf353d445f9.js.map  5.58 MB       2  [emitted]         main
    vendor.4b10ea08cbe243fbd96b.js.map   5.7 MB       3  [emitted]         vendor
  manifest.1a29b82ab404008e9de7.js.map  8.29 kB       4  [emitted]         manifest
                            index.html  1.53 kB          [emitted]         
[+HaM] ./~/@phosphor/messaging/lib/index.js 18.5 kB {3} [built]
[/sZe] ./~/@phosphor/commands/lib/index.js 33.2 kB {3} [built]
[2Kj9] ./~/@phosphor/widgets/lib/index.js 1.34 kB {3} [built]
[CUbq] ./~/@phosphor/signaling/lib/index.js 18.1 kB {3} [built]
[GiK3] ./~/react/index.js 190 bytes {3} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {3} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {3} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {3} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {3} [built]
[qzHn] ./~/@phosphor/coreutils/lib/index.js 721 bytes {3} [built]
[rplX] ./~/whatwg-fetch/fetch.js 13 kB {2} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {3} [built]
   [6] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {3} [built]
   [7] multi whatwg-fetch ./build/index.out.js 40 bytes {2} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {3} [built]
    + 1501 hidden modules
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.41 kB {0} [built]
Done in 39.09s.
```

And this is my conda env:
```
alabaster                 0.7.10                   py36_1    conda-forge
altair                    1.2.1                      py_0    conda-forge
arrow-cpp                 0.9.0                    py36_6    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
autopep8                  1.3.4                      py_0    conda-forge
babel                     2.5.3                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.5                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bokeh                     0.12.15                  py36_0  
boost                     1.63.0           py36h415b752_1    rdkit
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.1.18                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
cairocffi                 0.8.0                     <pip>
CairoSVG                  2.1.3                     <pip>
certifi                   2018.1.18                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.2                      py_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
cssselect2                0.2.1                     <pip>
cycler                    0.10.0                   py36_0    conda-forge
cytoolz                   0.9.0.1                  py36_0    conda-forge
dask                      0.17.2                     py_0    conda-forge
dask-core                 0.17.2                     py_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.2.1                    py36_0    conda-forge
defusedxml                0.5.0                     <pip>
distributed               1.21.6                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
easydict                  1.7                       <pip>
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                         0    conda-forge
flake8                    3.5.0                    py36_0    conda-forge
flask                     0.12.2                   py36_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.3a1                    py36_0    conda-forge
glib                      2.55.0                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
greenlet                  0.4.13                   py36_0    conda-forge
grequests                 0.3.0                    py36_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
holoviews                 1.10.0                     py_0    ioam
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                          0    conda-forge
idisplay                  0.1.2                     <pip>
idna                      2.6                      py36_1    conda-forge
imagesize                 1.0.0                    py36_0    conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.3.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.2.0                    py36_0    conda-forge
itsdangerous              0.24                       py_2    conda-forge
jedi                      0.11.1                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
jupyterlab                0.31.12                  py36_1    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
lancet                    0.9.0                    py36_0    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
locket                    0.2.0                    py36_1    conda-forge
lxml                      4.2.1                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
memory_profiler           0.52.0                   py36_0    conda-forge
mistune                   0.8.3                      py_0    conda-forge
msgpack-python            0.5.6                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                           1    rdkit
networkx                  2.1                      py36_0    conda-forge
notebook                  5.4.1                    py36_0    conda-forge
numpy                     1.14.2          py36_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.45.1                   py36_0    conda-forge
openblas                  0.2.20                        7    conda-forge
openssl                   1.0.2n                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.22.0                   py36_0    conda-forge
pandoc                    2.1.3                         0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
param                     1.6.0                         2    conda-forge
parquet-cpp               1.4.0                         0    conda-forge
parso                     0.1.1                      py_0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
patsy                     0.5.0                    py36_0    conda-forge
pcre                      8.41                          1    conda-forge
pexpect                   4.4.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    5.1.0                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.3                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py3Dmol                   0.7.0                     <pip>
pyarrow                   0.9.0                    py36_1    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyopenssl                 17.5.0                   py36_1    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.2                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2                         7    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
rdkit                     2017.09.3.0              py36_1    rdkit
readline                  7.0                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
requests-cache            0.4.13                   py36_0    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.1           py36_blas_openblas_200  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                39.0.1                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snakeviz                  0.4.2            py36h8fadade_0  
snowballstemmer           1.2.1                    py36_0    conda-forge
sortedcontainers          1.5.9                    py36_0    conda-forge
sphinx                    1.7.2                    py36_0    conda-forge
sphinxcontrib-websupport  1.0.1                    py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tinycss2                  0.6.1                     <pip>
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
vega                      0.4.4                    py36_1    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
widgetsnbextension        3.2.0                    py36_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.5                         1    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

This is on Ubuntu 17.10, 64bit.

Many thanks for your help.

Kind regards,  
Axel

**Comment by apahl** [comment]
After trying again today with the newest versions of JupyterLab (0.32.0), Holoviews (1.10.1) and the extension, it now works.  
Now I can finally switch to JupyterLab. Thanks for your efforts.

Kind regards,  
Axel
